# Generated by Django 5.0.6 on 2024-05-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="profilePicture/default_avatar.png",
                upload_to="profilePicture",
            ),
        ),
    ]
