version: '3'

services:
  app:
    image: 826546/docker101tutorial:apline-dj-uwsgi-1.0
    # build:
    #   context: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8080"
    environment:
      - DEBUG=1