version: "3.9"

services:
  django:
    image: django-docker:1.0
    build:
      context: .
    ports:
      - "8080:8000"
    volumes:
      - ./src:/src
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
